package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig roadTimeDaoConfig;

    private final RoadTimeDao roadTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        roadTimeDaoConfig = daoConfigMap.get(RoadTimeDao.class).clone();
        roadTimeDaoConfig.initIdentityScope(type);

        roadTimeDao = new RoadTimeDao(roadTimeDaoConfig, this);

        registerDao(RoadTime.class, roadTimeDao);
    }
    
    public void clear() {
        roadTimeDaoConfig.getIdentityScope().clear();
    }

    public RoadTimeDao getRoadTimeDao() {
        return roadTimeDao;
    }

}
