package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROAD_TIME".
 */
public class RoadTime {

    /** Not-null value. */
    private String road_name;
    private Integer stop_time;

    public RoadTime() {
    }

    public RoadTime(String road_name) {
        this.road_name = road_name;
    }

    public RoadTime(String road_name, Integer stop_time) {
        this.road_name = road_name;
        this.stop_time = stop_time;
    }

    /** Not-null value. */
    public String getRoad_name() {
        return road_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoad_name(String road_name) {
        this.road_name = road_name;
    }

    public Integer getStop_time() {
        return stop_time;
    }

    public void setStop_time(Integer stop_time) {
        this.stop_time = stop_time;
    }

}
